### ISSUE TITLE
Unexpected keywork argument 'device'

### ISSUE THREAD

**Issue by vamsee9201** [makit/makit-llm-lambda#1]
import json
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
from langchain.llms import GPT4All

# A default template that will be combined with the input to form the prompt
template = """The player performs the action: {action} What happens next?"""
prompt = PromptTemplate(template=template, input_variables=["action"])

# The location of the model to load
local_path = "/Users/vamseekrishna/Desktop/LLM/ggml-model-gpt4all-falcon-q4_0.bin"

# LangChain code to load the GPT4ALL model
llm = GPT4All(model=local_path, verbose=True)
llm_chain = LLMChain(prompt=prompt, llm=llm)

def handler(event, context):

    # Load an "action" from the request body
    body = json.loads(event.get("body", "{}"))
    action = body.get("action")
    
    # Basic validation
    if action is None:
        return {
            'statusCode': 400,
            'body': json.dumps({'error': 'No action was provided'})
        }

    # Where all the work happens
    response  = llm_chain.run(action)

    # Return the full response in JSON format
    return {
        'statusCode': 200,
        'body': json.dumps(response)
    }
    
    the above is my code.
    
    
this is my error message :

File "/Users/vamseekrishna/Desktop/LLM/GPTALL_test.py", line 14, in <module>
    llm = GPT4All(model=local_path, verbose=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vamseekrishna/Desktop/LLM/.llmenv/lib/python3.11/site-packages/langchain_core/load/serializable.py", line 107, in __init__
    super().__init__(**kwargs)
  File "/Users/vamseekrishna/Desktop/LLM/.llmenv/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  GPT4All.__init__() got an unexpected keyword argument 'device' (type=type_error)
  
  please help me solve it. Thank you.

**Comment by makit** [comment]
Hi, the newer versions of GPT4ALL and Langchain had breaking changes, especially when running with the older model I used. I have uplifted the code, and pinned the versions. I've also suggested a different model.

Could you try the latest recommended model, and update your virtual environment with the pinned dependencies to check if that resolves your issue.

Thanks
